### ISSUE TITLE
Official pytorch tutorials

### ISSUE THREAD

**Issue by chsasank** [rguthrie3/DeepLearningForNLPInPytorch#5]
Hi,

We've included your tutorial in official pytorch tutorials [here](http://pytorch.org/tutorials/beginner/deep_learning_nlp_tutorial.html).
it'll be useful for community to have all the awesome tutorials in one place. I also think that html documentation is more approachable than a notebook.

The current page is almost exactly same as your notebook. I've just raised a [PR](https://github.com/pytorch/tutorials/pull/60) to break the tutorial into a few parts to make each bite-sized. Would you approve of such a reorganisation? Your feedback would be valuable.

You can contact me at sasankchilamkurthy@gmail.com

Sasank.

**Comment by rguthrie3** [comment]
Sure, this is fine.  I'm happy for it to be included in the tutorials repo.  You are free to make formatting changes as you want (the split you came up with is probably what I would have done, so that is fine).  If people comment on improvements or find bugs, you can let me know or point them to open an issue here and I can handle it.

**Comment by chsasank** [comment]
Thanks a lot!
