### ISSUE TITLE
Batch Data Loading and Processing

### ISSUE THREAD

**Issue by manasRK** [rguthrie3/DeepLearningForNLPInPytorch#7]
Any plan to convert some of the code base (like the LSTM/NER) to allow for minibatch processing? 
Currently, all of them take one instance at a time. Any pointers in that regard would be useful as well.

**Comment by rguthrie3** [comment]
Typically, minibatching adds a substantial amount of confusion in the implementation, since one has to keep track of what each axis of your tensors means.  Since this is a tutorial, I intentionally did not use minibatching because I wanted to avoid making it substantially more confusing without much return on educational value.  So I don't plan to do anything about minibatching in this tutorial.  I don't have any specific tips for implementing minibatching.  It is just about staying organized and clean with how you arrange your tensors.
